FROM node:18.14.2-bullseye-slim

ENV MONGO_HOST localhost
ENV MONGO_PORT 27017

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY --chown=node:node . .

EXPOSE 8080

USER node
ENTRYPOINT [ "./entrypoint.sh" ]
CMD [ "node", "./server.js" ]
